In [1]:
# Numpy library is core library for scintific computing, 
#provides high performance multi dimensional array object.
# and tools to work with these arrays.

In [3]:
import numpy as np

In [39]:
a=np.array([1,2,3], dtype=np.int64)
a

array([1, 2, 3], dtype=int64)

In [8]:
b=np.array([[1,2,3],[2,3,4]])

In [9]:
c=np.array([[1,2],[2,3],[3,4]])

In [10]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [16]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [17]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [20]:
np.linspace(0,5,5,2)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [21]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [30]:
np.random.random((3,2))

array([[0.30003047, 0.04031791],
       [0.8815637 , 0.78064582],
       [0.96269715, 0.70745157]])

In [27]:
e=np.empty((2,2))

In [28]:
e

array([[0.59549301, 0.05734676],
       [0.62540158, 0.00915286]])

In [50]:
e=np.eye(3,2)
e

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [52]:
a=np.full((2,2),2)
b=np.full((2,2),3)

In [53]:
a+b

array([[5, 5],
       [5, 5]])

In [55]:
a*b

array([[6, 6],
       [6, 6]])

In [60]:
a@b

array([[12, 12],
       [12, 12]])

In [85]:
a.dot(b)

array([[12, 12],
       [21, 21]])

In [59]:
np.multiply(a,b)

array([[6, 6],
       [6, 6]])

In [57]:
a/b

array([[0.66666667, 0.66666667],
       [0.66666667, 0.66666667]])

In [61]:
a==b

array([[False, False],
       [False, False]])

In [65]:
np.array_equal(a,b)

False

In [66]:
a.sum()

8

In [67]:
a.min()

2

In [70]:
a.sum(axis=0)

array([4, 4])

In [71]:
a.mean()

2.0

In [73]:
a.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [76]:
np.std(a)

0.0

In [83]:
a=np.full((2,2),2)

In [84]:
a[1,1]=5
a

array([[2, 2],
       [2, 5]])

In [90]:
a[a<=5]

array([2, 2, 2, 5])

In [95]:
a[0,1]=3
a

array([[2, 3],
       [2, 5]])

In [96]:
a.T

array([[2, 2],
       [3, 5]])

In [99]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
b[:1]

array([[1, 2, 3]])

In [102]:
b[:1,:2]

array([[1, 2]])

In [103]:
b.ravel()

array([1, 2, 3, 4, 5, 6])

In [104]:
b.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [107]:
b.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
np.hsplit(b,3)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [111]:
np.vsplit(b,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [112]:
a

array([[2, 3],
       [2, 5]])

In [113]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
np.concatenate((a,b),axis=1)

array([[2, 3, 1, 2, 3],
       [2, 5, 4, 5, 6]])

In [119]:
np.concatenate((a,b.T),axis=0)

array([[2, 3],
       [2, 5],
       [1, 4],
       [2, 5],
       [3, 6]])

In [134]:
768/10

76.8

In [135]:
list=[]
list.append(0)
list

[0]

In [137]:
1000000000000000000000000000466%10

6

In [142]:
int(1000000000000000000000000000466//10)

100000000000000000000000000046

In [152]:
s=" s"
str1=[s[i] for i in range(len(s))]
str1

[' ', 's']

In [153]:
str1[:1]

[' ']

In [156]:
s="abcab"
s[1:]

'bcab'

In [157]:
str1=list[s]

TypeError: list indices must be integers or slices, not str

In [158]:
75%2

1

In [160]:
74//2

37

In [161]:
75//2

37

In [162]:
99//2

49

In [163]:
100//2

50

In [170]:
a=np.array([[5, 3, 0, 0, 7 ,0 ,0 ,0, 0],
[5 ,6, 0 ,8, 4, 7 ,0 ,0, 0]])
a

array([[5, 3, 0, 0, 7, 0, 0, 0, 0],
       [5, 6, 0, 8, 4, 7, 0, 0, 0]])

In [171]:
a,b,c = np.hsplit(a,3)
b

array([[0, 7, 0],
       [8, 4, 7]])

In [174]:
x=np.concatenate((a,b,c), axis=0)

In [175]:
x

array([[5, 3, 0],
       [5, 6, 0],
       [0, 7, 0],
       [8, 4, 7],
       [0, 0, 0],
       [0, 0, 0]])

In [179]:
x[3:6]

array([[8, 4, 7],
       [0, 0, 0],
       [0, 0, 0]])

In [185]:
set

set

In [186]:
1//3

0

In [187]:
2//3

0

In [188]:
3//3

1

In [189]:
4//3

1

In [230]:
l=[1,2,3]

In [201]:
l.reverse()

In [227]:
l

[3]

In [231]:
l2=[3,5,6]
l6=[0,6,9]

In [232]:
l3=[l,l2,l6]
l3

[[1, 2, 3], [3, 5, 6], [0, 6, 9]]

In [233]:
for row in l3:
    print(l3)
    row.pop()

[[1, 2, 3], [3, 5, 6], [0, 6, 9]]
[[1, 2], [3, 5, 6], [0, 6, 9]]
[[1, 2], [3, 5], [0, 6, 9]]


In [223]:
l5 = [[1,2,3],[5,6,7,8,9]]
l5.pop()[::-1]

[9, 8, 7, 6, 5]

In [217]:
l3

[[3, 5, 6]]

In [207]:
np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20],[21,22,23,24]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])